slice_name: Active Orders
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 76__table
  viz_type: pivot_table_v2
  slice_id: 239
  groupbyColumns: []
  groupbyRows:
  - datasourceWarning: false
    expressionType: SQL
    label: Customer
    sqlExpression: customer
  - cs_person
  - datasourceWarning: false
    expressionType: SQL
    label: Vessel Voyage
    sqlExpression: vessel_voyage
  - datasourceWarning: false
    expressionType: SQL
    label: Shipping Line
    sqlExpression: shipping_line
  - datasourceWarning: false
    expressionType: SQL
    label: POD
    sqlExpression: pod_name
  - datasourceWarning: false
    expressionType: SQL
    label: Commodity
    sqlExpression: commodity
  - datasourceWarning: false
    expressionType: SQL
    label: ETD
    sqlExpression: etd
  time_grain_sqla: P1D
  temporal_columns_lookup:
    booking_confirmed_date: true
    booking_placed_date: true
    booking_shared_with_customer_date: true
    created_at: true
    etd: true
    gate_close_cutoff: true
    valid_till_date: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: pickedup
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1289
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: PickedUp
    optionName: metric_89srkzc9o8_5y1mdcjrvxl
    sqlExpression: null
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Pickup Pending
    optionName: metric_ipboulby8ik_y42tkhp1obp
    sqlExpression: sum((pickup_pending))
  - aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2024-10-07T10:24:18.740377'
      column_name: pol_gated_in
      created_on: '2024-10-07T10:24:18.740376'
      description: null
      expression: null
      extra: '{"warning_markdown":null}'
      filterable: true
      groupby: true
      id: 1291
      is_active: true
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      uuid: 886ee910-1105-48da-bde3-eaa5112b3fac
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Gated In
    optionName: metric_52u2fpa5wu6_w3wj204dvn
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2024-10-07T11:57:20.909522'
      column_name: Gate In Pending
      created_on: '2024-10-07T11:57:20.909518'
      description: null
      expression: pickedup - pol_gated_in
      extra: '{}'
      filterable: true
      groupby: true
      id: 1337
      is_active: true
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      uuid: 0af368c2-338e-489d-88ec-5f9f9e762452
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Gate in Pending
    optionName: metric_nq7503ot16f_otd1fd4r7dn
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2024-10-07T10:24:18.740393'
      column_name: loaded
      created_on: '2024-10-07T10:24:18.740392'
      description: null
      expression: null
      extra: '{"warning_markdown":null}'
      filterable: true
      groupby: true
      id: 1292
      is_active: true
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      uuid: 4515f3f9-6ea8-4a80-8497-da2a6ec1be87
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Loaded
    optionName: metric_gjufrumimi_qcj6tcpk8rp
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2024-10-07T10:24:18.740410'
      column_name: loading_pending
      created_on: '2024-10-07T10:24:18.740409'
      description: null
      expression: null
      extra: '{"warning_markdown":null}'
      filterable: true
      groupby: true
      id: 1293
      is_active: true
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      uuid: c95b5494-c4fc-48a2-8879-c045bc7c8b91
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Loading Pending
    optionName: metric_4exc5t2cwg1_vuxe7rx5pl
    sqlExpression: null
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_jikth89gn5_k0o4odzd2s
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade_type
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_poo9q7gsrjo_w49tj6jz9p
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: etd
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  expandCollapse: true
  colTotals: true
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: value_z_to_a
  colOrder: key_a_to_z
  conditional_formatting:
  - colorScheme: '#CDFEE1'
    column: PickedUp
    operator: None
  - colorScheme: '#FFEF9D'
    column: Pickup Pending
    operator: None
  - colorScheme: '#CDFEE1'
    column: Gated In
    operator: None
  - colorScheme: '#FFEF9D'
    column: Gate in Pending
    operator: None
  - colorScheme: '#CDFEE1'
    column: Loaded
    operator: None
  - colorScheme: '#FFEF9D'
    column: Loading Pending
    operator: None
  extra_form_data: {}
  dashboards:
  - 6
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: a8a088b9-0647-48e3-ade7-89930e41c463
version: 1.0.0
dataset_uuid: 409d613f-b962-4e9d-94a6-0b0ec54c3e85
