slice_name: Branch wise DSO Trend
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 5__table
  viz_type: echarts_timeseries_line
  slice_id: 14
  x_axis: posting_date
  time_grain_sqla: P1M
  metrics:
  - DSO
  groupby:
  - label: Branch
    sqlExpression: cost_center
    expressionType: SQL
  adhoc_filters:
  - expressionType: SIMPLE
    subject: posting_date
    operator: TEMPORAL_RANGE
    comparator: Last year
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_c5kr79t2tql_fihmg6arrei
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  rolling_type: null
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  stack: null
  only_total: true
  area: true
  opacity: 0.2
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 3
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"filters":[{"col":"posting_date","op":"TEMPORAL_RANGE","val":"Last
  year"}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"posting_date","label":"posting_date","expressionType":"SQL"},{"label":"Branch","sqlExpression":"cost_center","expressionType":"SQL"}],"metrics":["DSO"],"orderby":[["DSO",false]],"annotation_layers":[],"row_limit":10000,"series_columns":[{"label":"Branch","sqlExpression":"cost_center","expressionType":"SQL"}],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["posting_date"],"columns":["Branch"],"aggregates":{"DSO":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"DSO":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"5__table","viz_type":"echarts_timeseries_line","slice_id":14,"x_axis":"posting_date","time_grain_sqla":"P1M","metrics":["DSO"],"groupby":[{"label":"Branch","sqlExpression":"cost_center","expressionType":"SQL"}],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"posting_date","operator":"TEMPORAL_RANGE","comparator":"Last
  year","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_c5kr79t2tql_fihmg6arrei"}],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"rolling_type":null,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","stack":null,"only_total":true,"area":true,"opacity":0.2,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"bottom","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","logAxis":false,"truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[3],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: ddadf0c8-2de4-45d2-924c-297ff31488e8
version: 1.0.0
dataset_uuid: 3354e233-093d-4b66-b483-21aeb019e28c
