slice_name: Carrier wise ETA Performance - TTM
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 100__table
  viz_type: echarts_timeseries_bar
  slice_id: 254
  x_axis: carrier
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - count
  groupby:
  - eta_status
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_f4m77etmq1j_8q6ss60ae5p
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: container_created_at
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_2qis3u9y8ew_5h6zmb7lqan
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: eta_status is not NULL
    subject: null
  - clause: WHERE
    comparator: Last year
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_4fw1hm1slx4_09ofo32pd2jt
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_wver50uve5c_59hya0gc6b6
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade_type
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  annotation_layers: []
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: max
  color_scheme: supersetColors
  stack: Stack
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 6
query_context: null
cache_timeout: null
uuid: 38efbf4e-c63c-4aba-8566-03617e00aad8
version: 1.0.0
dataset_uuid: 2938bd1f-22ad-4635-8dc5-2a3ac41c98c8
