slice_name: Carrier Released > 2 Days
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 75__table
  viz_type: big_number_total
  slice_id: 125
  metric: Shipment Documents
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: carrier_released is not NULL
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_dp4d72bycfw_5kf7122lb73
  - expressionType: SIMPLE
    subject: carrier_tat
    operator: '>'
    operatorId: GREATER_THAN
    comparator: 2
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_ocz9w27884c_g0y5hnn5f1p
  - expressionType: SIMPLE
    subject: type_of_bl
    operator: IN
    operatorId: IN
    comparator:
    - master
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_zb0wdvscxgr_gh0xosx2fxs
  - expressionType: SIMPLE
    subject: ship_type
    operator: IN
    operatorId: IN
    comparator:
    - consol
    - back_to_back
    - direct
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_zp8ovpc4uh_5i0fruaomhc
  - expressionType: SIMPLE
    subject: jed
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_85ctufij1c_uzok65ojfvm
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 9
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 4ae133f4-03fa-4423-afb1-b1031e7ce855
version: 1.0.0
dataset_uuid: 4fc51f9b-3504-4494-9dde-c1ff47aec07c
