slice_name: Carriers Wise Monthly Prov Margin - OE
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 71__table
  viz_type: pivot_table_v2
  slice_id: 940
  groupbyColumns:
  - JED Month (Numeric)
  groupbyRows:
  - carrier_sf
  temporal_columns_lookup:
    jed: true
    job_close_date: true
    onboarded_on: true
    customer_created_at: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: prov_margin
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4393
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: Prov Margin
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Prov GP
    optionName: metric_z9nk0ar7tcg_i3gjt7hczqf
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_51l3x06mray_x7lvr666l3i
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ayvpi6qq3gr_3iqp094bp2x
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_4qedl6zb4ze_6wlwjkefpij
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  row_limit: '100000'
  order_desc: true
  aggregateFunction: Sum
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting:
  - colorScheme: '#E8EBFE'
    column: Prov GP (Lakhs)
    operator: None
  extra_form_data: {}
  dashboards:
  - 64
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: e6e0e2b8-acb0-413e-b880-143054356ca8
version: 1.0.0
dataset_uuid: ed854b24-dc83-420a-b942-0ac77d1d6be1
