slice_name: Customer release > 5 Days
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 75__table
  viz_type: big_number_total
  slice_id: 551
  metric: Shipment Documents
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: carrier_released is not NULL
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_dp4d72bycfw_5kf7122lb73
  - expressionType: SQL
    sqlExpression: given_to_customer_at is not null or surrendered_at_origin_at is
      not NULL
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_ca5rrgwgofi_ayvm2o8317n
  - expressionType: SIMPLE
    subject: ship_type
    operator: IN
    operatorId: IN
    comparator:
    - direct
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_6c64fosyig5_bv3ast6so5
  - expressionType: SIMPLE
    subject: Customer release TAT
    operator: '>'
    operatorId: GREATER_THAN
    comparator: '5'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_5lc9fk5fgk_cxq3bmujyxa
  - expressionType: SIMPLE
    subject: jed
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_85ctufij1c_uzok65ojfvm
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: f10d5906-f48b-4140-8031-6e8347638d84
version: 1.0.0
dataset_uuid: 4fc51f9b-3504-4494-9dde-c1ff47aec07c
