slice_name: Customer Wise Comparisons of Margin from Prev Period - OE
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 9__table
  viz_type: pivot_table_v2
  slice_id: 919
  groupbyColumns: []
  groupbyRows:
  - customer
  temporal_columns_lookup:
    jed: true
    job_close_date: true
    onboarded_on: true
    customer_created_at: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: GP This Week
      description: null
      expression: "CASE  \n    WHEN jed >= date_trunc('week', current_date)  \n  \
        \       AND jed < date_trunc('week', current_date + interval '1 week')  \n\
        \    THEN actual_gp\n    ELSE 0  \n  END\n"
      filterable: true
      groupby: true
      id: 4330
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Margin This Week
    optionName: metric_7a5ngadgcsn_jx3sm0377u
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: GP Prev Week
      description: null
      expression: "CASE  \n    WHEN jed >= date_trunc('week', current_date) - interval\
        \ '1 week'  \n    AND jed < date_trunc('week', current_date)  \n    THEN actual_gp\n\
        \    ELSE 0  \nEND  \n"
      filterable: true
      groupby: true
      id: 4329
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Margin Prev Week
    optionName: metric_h1hmplin50l_qbhofq4cqkl
  - Weekly Avg GP
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: GP MTD
      description: null
      expression: "CASE WHEN \njed >= date_trunc('month', current_date)\nAND jed <\
        \ current_date \nTHEN actual_gp\nELSE 0 \nEND"
      filterable: true
      groupby: true
      id: 4332
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Margin MTD
    optionName: metric_e32mqhctuu5_1cde1fy2yui
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: GP MTD - Prior
      description: null
      expression: "CASE WHEN jed >= date_trunc('month', current_date) - interval '1\
        \ year'\n              AND jed < date_trunc('month', current_date) - interval\
        \ '1 year' + (current_date - date_trunc('month', current_date)) \n       \
        \  THEN actual_gp\n         ELSE 0 \n    END"
      filterable: true
      groupby: true
      id: 4331
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Margin MTD Prev Year
    optionName: metric_3l8kp3usbkc_tjmvuv95u1
  - Monthly Avg GP
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: GP YTD - Current
      description: GP YTD till the current date
      expression: "CASE \n        WHEN jed >= date_trunc('year', current_date)\n \
        \            AND jed < current_date\n        THEN actual_gp\n        ELSE\
        \ 0\n    END"
      filterable: true
      groupby: true
      id: 680
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Margin YTD
    optionName: metric_cwi1vwvi446_4vmqdjb57uh
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: GP YTD - Previous
      description: GP Previous Year - But not upto the same YTD
      expression: "CASE \n        WHEN jed >= date_trunc('year', current_date - interval\
        \ '1 year') \n             AND jed < (current_date - interval '1 year') \n\
        \        THEN actual_gp \n        ELSE 0 \n    END"
      filterable: true
      groupby: true
      id: 2179
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Margin YTD Prev Year
    optionName: metric_vuqf698n3yg_pjff4xddm6e
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_51l3x06mray_x7lvr666l3i
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ayvpi6qq3gr_3iqp094bp2x
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_4qedl6zb4ze_6wlwjkefpij
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  row_limit: '100000'
  order_desc: true
  aggregateFunction: Sum
  colTotals: true
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting:
  - colorScheme: '#E8EBFE'
    column: GP This Week (Lakhs)
    operator: None
  - colorScheme: '#E0F0FF'
    column: GP Prev Week (Lakhs)
    operator: None
  - colorScheme: '#FFEF9D'
    column: Weekly Avg GP (Lakhs)
    operator: None
  - colorScheme: '#E6FFFB'
    column: GP MTD (Lakhs)
    operator: None
  - colorScheme: '#87E8DE'
    column: GP MTD Prev Year (Lakhs)
    operator: None
  - colorScheme: '#EAFF8F'
    column: Monthly Avg GP (Lakhs)
    operator: None
  - colorScheme: '#E0F0FF'
    column: GP YTD
    operator: None
  - colorScheme: '#E8EBFE'
    column: GP YTD Prev
    operator: None
  extra_form_data: {}
  dashboards:
  - 64
query_context: '{"datasource":{"id":9,"type":"table"},"force":false,"queries":[{"filters":[{"col":"freight","op":"IN","val":["ocean"]},{"col":"trade","op":"IN","val":["export"]},{"col":"jed","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["customer"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  This Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date)  \n         AND jed < date_trunc(''week'', current_date + interval
  ''1 week'')  \n    THEN actual_gp\n    ELSE 0  \n  END\n","filterable":true,"groupby":true,"id":4330,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  This Week","optionName":"metric_7a5ngadgcsn_jx3sm0377u"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  Prev Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date) - interval ''1 week''  \n    AND jed < date_trunc(''week'', current_date)  \n    THEN
  actual_gp\n    ELSE 0  \nEND  \n","filterable":true,"groupby":true,"id":4329,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  Prev Week","optionName":"metric_h1hmplin50l_qbhofq4cqkl"},"Weekly Avg GP",{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  MTD","description":null,"expression":"CASE WHEN \njed >= date_trunc(''month'', current_date)\nAND
  jed < current_date \nTHEN actual_gp\nELSE 0 \nEND","filterable":true,"groupby":true,"id":4332,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  MTD","optionName":"metric_e32mqhctuu5_1cde1fy2yui"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  MTD - Prior","description":null,"expression":"CASE WHEN jed >= date_trunc(''month'',
  current_date) - interval ''1 year''\n              AND jed < date_trunc(''month'',
  current_date) - interval ''1 year'' + (current_date - date_trunc(''month'', current_date))
  \n         THEN actual_gp\n         ELSE 0 \n    END","filterable":true,"groupby":true,"id":4331,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  MTD Prev Year","optionName":"metric_3l8kp3usbkc_tjmvuv95u1"},"Monthly Avg GP",{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  YTD - Current","description":"GP YTD till the current date","expression":"CASE \n        WHEN
  jed >= date_trunc(''year'', current_date)\n             AND jed < current_date\n        THEN
  actual_gp\n        ELSE 0\n    END","filterable":true,"groupby":true,"id":680,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  YTD","optionName":"metric_cwi1vwvi446_4vmqdjb57uh"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  YTD - Previous","description":"GP Previous Year - But not upto the same YTD","expression":"CASE
  \n        WHEN jed >= date_trunc(''year'', current_date - interval ''1 year'') \n             AND
  jed < (current_date - interval ''1 year'') \n        THEN actual_gp \n        ELSE
  0 \n    END","filterable":true,"groupby":true,"id":2179,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  YTD Prev Year","optionName":"metric_vuqf698n3yg_pjff4xddm6e"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  This Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date)  \n         AND jed < date_trunc(''week'', current_date + interval
  ''1 week'')  \n    THEN actual_gp\n    ELSE 0  \n  END\n","filterable":true,"groupby":true,"id":4330,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  This Week","optionName":"metric_7a5ngadgcsn_jx3sm0377u"},false]],"annotation_layers":[],"row_limit":100000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"9__table","viz_type":"pivot_table_v2","slice_id":919,"groupbyColumns":[],"groupbyRows":["customer"],"temporal_columns_lookup":{"jed":true,"job_close_date":true,"onboarded_on":true,"customer_created_at":true},"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  This Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date)  \n         AND jed < date_trunc(''week'', current_date + interval
  ''1 week'')  \n    THEN actual_gp\n    ELSE 0  \n  END\n","filterable":true,"groupby":true,"id":4330,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  This Week","optionName":"metric_7a5ngadgcsn_jx3sm0377u"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  Prev Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date) - interval ''1 week''  \n    AND jed < date_trunc(''week'', current_date)  \n    THEN
  actual_gp\n    ELSE 0  \nEND  \n","filterable":true,"groupby":true,"id":4329,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  Prev Week","optionName":"metric_h1hmplin50l_qbhofq4cqkl"},"Weekly Avg GP",{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  MTD","description":null,"expression":"CASE WHEN \njed >= date_trunc(''month'', current_date)\nAND
  jed < current_date \nTHEN actual_gp\nELSE 0 \nEND","filterable":true,"groupby":true,"id":4332,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  MTD","optionName":"metric_e32mqhctuu5_1cde1fy2yui"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  MTD - Prior","description":null,"expression":"CASE WHEN jed >= date_trunc(''month'',
  current_date) - interval ''1 year''\n              AND jed < date_trunc(''month'',
  current_date) - interval ''1 year'' + (current_date - date_trunc(''month'', current_date))
  \n         THEN actual_gp\n         ELSE 0 \n    END","filterable":true,"groupby":true,"id":4331,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  MTD Prev Year","optionName":"metric_3l8kp3usbkc_tjmvuv95u1"},"Monthly Avg GP",{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  YTD - Current","description":"GP YTD till the current date","expression":"CASE \n        WHEN
  jed >= date_trunc(''year'', current_date)\n             AND jed < current_date\n        THEN
  actual_gp\n        ELSE 0\n    END","filterable":true,"groupby":true,"id":680,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  YTD","optionName":"metric_cwi1vwvi446_4vmqdjb57uh"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"GP
  YTD - Previous","description":"GP Previous Year - But not upto the same YTD","expression":"CASE
  \n        WHEN jed >= date_trunc(''year'', current_date - interval ''1 year'') \n             AND
  jed < (current_date - interval ''1 year'') \n        THEN actual_gp \n        ELSE
  0 \n    END","filterable":true,"groupby":true,"id":2179,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Margin
  YTD Prev Year","optionName":"metric_vuqf698n3yg_pjff4xddm6e"}],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":["ocean"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_51l3x06mray_x7lvr666l3i","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"freight"},{"clause":"WHERE","comparator":["export"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_ayvpi6qq3gr_3iqp094bp2x","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"trade"},{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_4qedl6zb4ze_6wlwjkefpij","isExtra":true,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"jed"}],"row_limit":"100000","order_desc":true,"aggregateFunction":"Sum","colTotals":true,"valueFormat":"SMART_NUMBER","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[{"colorScheme":"#E8EBFE","column":"GP
  This Week (Lakhs)","operator":"None"},{"colorScheme":"#E0F0FF","column":"GP Prev
  Week (Lakhs)","operator":"None"},{"colorScheme":"#FFEF9D","column":"Weekly Avg GP
  (Lakhs)","operator":"None"},{"colorScheme":"#E6FFFB","column":"GP MTD (Lakhs)","operator":"None"},{"colorScheme":"#87E8DE","column":"GP
  MTD Prev Year (Lakhs)","operator":"None"},{"colorScheme":"#EAFF8F","column":"Monthly
  Avg GP (Lakhs)","operator":"None"},{"colorScheme":"#E0F0FF","column":"GP YTD","operator":"None"},{"colorScheme":"#E8EBFE","column":"GP
  YTD Prev","operator":"None"}],"extra_form_data":{},"dashboards":[64],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 28618997-8464-4a93-8c30-2f5985b10ce5
version: 1.0.0
dataset_uuid: ed854b24-dc83-420a-b942-0ac77d1d6be1
