slice_name: DPO Trend
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 106__table
  viz_type: echarts_timeseries_bar
  slice_id: 315
  x_axis: posting_date
  time_grain_sqla: P1M
  metrics:
  - DPO - 30 Days
  groupby: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: posting_date
    operator: TEMPORAL_RANGE
    comparator: Last year
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_mw00rllitk_7igp8ckvboj
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  rolling_type: null
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  show_legend: true
  legendType: scroll
  legendOrientation: top
  y_axis_format: SMART_NUMBER
  logAxis: true
  truncateXAxis: true
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
query_context: null
cache_timeout: null
uuid: b1ccb87d-88d9-43a4-a84c-b8cf1e4a3e07
version: 1.0.0
dataset_uuid: f5bead0e-a014-48fa-80b2-86e1403f8380
