slice_name: Estimated Revenue  - OE
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 71__table
  viz_type: big_number_total
  slice_id: 854
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: estimate_income
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4383
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: Estimated Income
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Actual Revenue
    optionName: metric_un80emb4p5l_5oeovqkd8l
  adhoc_filters:
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_qw9zuj54m3k_jad8uznf06
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_979gb4ccnhj_hbtjsopylkq
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_lhdi4xaxleo_pcbfut9lj99
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  header_font_size: 0.5
  subheader_font_size: 0.3
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 64
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 2e52dfe3-c7c8-41f9-b95c-f2da8d9d6acc
version: 1.0.0
dataset_uuid: ed854b24-dc83-420a-b942-0ac77d1d6be1
