slice_name: First Print Pending
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 75__table
  viz_type: big_number_total
  slice_id: 649
  metric: count
  adhoc_filters:
  - expressionType: SIMPLE
    subject: ship_type
    operator: IN
    operatorId: IN
    comparator:
    - direct
    - consol
    - back_to_back
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_83hoq3e0o9h_y8864t58t9e
  - expressionType: SQL
    sqlExpression: si_filed_at is not null AND draft_received_at is NULL
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_87j78d2hwjw_6l15vxojonn
  - expressionType: SQL
    sqlExpression: carrier_released is NULL
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_qo85plyin1a_ancfgd5l9hh
  - expressionType: SIMPLE
    subject: etd
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_unt6trmacti_0dn37vswvqzw
  header_font_size: 0.5
  subheader_font_size: 0.3
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 57
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: d07f956d-14a4-42cf-bd5e-c84d009719db
version: 1.0.0
dataset_uuid: 4fc51f9b-3504-4494-9dde-c1ff47aec07c
