slice_name: GP % Trend
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  datasource: 88__table
  viz_type: echarts_area
  slice_id: 313
  x_axis: inquiry_created_at
  time_grain_sqla: P1M
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - Won GP %
  groupby:
  - expressionType: SQL
    label: Quote Status
    sqlExpression: quote_status
    datasourceWarning: false
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_iuvd5s67e1d_yi90sg24hi
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: inquiry_created_at
  timeseries_limit_metric:
    aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: created_at
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 700
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: DATETIME
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(created_at)
    optionName: metric_twuympdyth_apjlgnhbl5c
    sqlExpression: null
  order_desc: true
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.2
  stack: null
  only_total: true
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: null
cache_timeout: null
uuid: 5eb743fd-66e5-4518-a47f-28ceb5ac673d
version: 1.0.0
dataset_uuid: 3f348298-40e0-4d14-99b3-efe47f94b006
