slice_name: Invoice wise Payable O/S
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 106__table
  viz_type: table
  slice_id: 317
  query_mode: aggregate
  groupby:
  - expressionType: SQL
    label: Invoice Number
    sqlExpression: real_voucher_number
  - expressionType: SQL
    label: Supplier
    sqlExpression: supplier
  - expressionType: SQL
    label: Invoice date
    sqlExpression: posting_date
  - expressionType: SQL
    label: Due date
    sqlExpression: due_date
  time_grain_sqla: P1M
  temporal_columns_lookup:
    due_date: true
    posting_date: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: net_os
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2040
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NEWDECIMAL
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Net Payable
    optionName: metric_o9ekpo2asis_xq5x9mdamsm
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Overdue Amount
      description: null
      expression: "CASE \n    WHEN CURDATE() > due_date THEN net_os\n    ELSE 0\n\
        END"
      filterable: true
      groupby: true
      id: 2050
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Overdue
    optionName: metric_coj7yd2vqns_9f4lc1q7zfl
    sqlExpression: null
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ecc1algt13d_8c5oy3kl1xm
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: posting_date
  - clause: WHERE
    comparator:
    - Purchase Invoice
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_803y8edr758_kdizp5ot2j
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: real_voucher_type
  timeseries_limit_metric:
    aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: posting_date
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2031
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: DATE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(posting_date)
    optionName: metric_w9tv3vjpkke_1gqwg4wxcih
    sqlExpression: null
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  show_totals: true
  table_timestamp_format: smart_date
  show_cell_bars: true
  color_pn: true
  conditional_formatting:
  - colorScheme: '#EFA1AA'
    column: Net Payable
    operator: None
  - colorScheme: '#EFA1AA'
    column: Overdue
    operator: None
  extra_form_data: {}
  dashboards:
  - 20
  comparison_type: values
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 74aff014-c1a1-4672-b8fb-4859255693bc
version: 1.0.0
dataset_uuid: f5bead0e-a014-48fa-80b2-86e1403f8380
