slice_name: Job Creation Pending
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 75__table
  viz_type: table
  slice_id: 656
  query_mode: aggregate
  groupby:
  - datasourceWarning: false
    expressionType: SQL
    label: 'Order #'
    sqlExpression: job_number_hyperlink
  - customer
  - sales_person
  - pol
  - pod
  - carrier
  - datasourceWarning: false
    expressionType: SQL
    label: Vessel Voyage
    sqlExpression: CONCAT(vessel,CONCAT('-', voyage))
  - etd
  - datasourceWarning: false
    expressionType: SQL
    label: SI CutOff
    sqlExpression: si_cutoff
  - days_since_etd
  temporal_columns_lookup:
    etd: true
    jed: true
    jobdate: true
    invoice_received_date: true
    invoice_paid_date: true
    si_cutoff: true
    si_received_from_customer_date: true
    gate_cutoff: true
    create_draft_at: true
    si_filed_at: true
    draft_received_at: true
    first_draft_shared_at: true
    draft_approved_at: true
    carrier_released: true
    given_to_customer_at: true
    surrendered_at_origin_at: true
    received_by_shipper_at: true
    event_date: true
    master_released_at: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2025-05-14T07:30:34.121283'
      column_name: container_count
      created_on: '2025-05-14T07:30:34.121281'
      description: null
      expression: null
      extra: '{}'
      filterable: true
      groupby: true
      id: 629
      is_active: true
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      uuid: 922ba9bc-b449-45cb-b4ed-2a7aed3765ca
      verbose_name: Container Count
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Containers
    optionName: metric_fip9114yim6_fgdtozfvyv6
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2025-05-14T07:30:34.123297'
      column_name: allocated_quantity
      created_on: '2025-05-14T07:30:34.123293'
      description: null
      expression: null
      extra: '{}'
      filterable: true
      groupby: true
      id: 3812
      is_active: true
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      uuid: 82a5d98f-d357-4711-a333-be4dc7ef5f0a
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Allocated
    optionName: metric_r5yf2y36ipc_grr91g37c0a
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2025-05-14T07:30:34.123938'
      column_name: quantity_picked_up
      created_on: '2025-05-14T07:30:34.123935'
      description: null
      expression: null
      extra: '{}'
      filterable: true
      groupby: true
      id: 3833
      is_active: true
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      uuid: f61f5afa-a5e9-47b1-a8fe-fd1ff77e3967
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Picked Up
    optionName: metric_3ixdcq8vdmx_7zwri7mvavp
    sqlExpression: null
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_5mexqurw3ar_o7gvkopl2a
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: 'job_number is NULL

      '
    subject: null
  - clause: WHERE
    comparator: 0
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_x7jiknodpk_cu8sy1rvk7t
    isExtra: false
    isNew: false
    operator: '>'
    operatorId: GREATER_THAN
    sqlExpression: null
    subject: allocated_quantity
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_unt6trmacti_0dn37vswvqzw
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: etd
  timeseries_limit_metric:
    aggregate: MIN
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: etd
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 621
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: DATETIME
      type_generic: 2
      verbose_name: ETD
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MIN(ETD)
    optionName: metric_a0zjjgtdtxr_fk0psri9ku
    sqlExpression: null
  order_by_cols: []
  row_limit: 1000
  order_desc: false
  table_timestamp_format: '%d-%m-%Y'
  show_cell_bars: true
  color_pn: true
  conditional_formatting:
  - colorScheme: '#E0F0FF'
    column: Containers
    operator: None
  - colorScheme: '#CDFEE1'
    column: Allocated
    operator: None
  - colorScheme: '#FFEF9D'
    column: Picked Up
    operator: None
  extra_form_data: {}
  dashboards:
  - 57
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: d1ae7861-ca38-4315-a678-888663e51796
version: 1.0.0
dataset_uuid: 4fc51f9b-3504-4494-9dde-c1ff47aec07c
