slice_name: LCL CBM Growth Compared to Previous Year - OE
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  datasource: 79__table
  viz_type: mixed_timeseries
  slice_id: 976
  x_axis: JED Month (Numeric)
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: CBM This Year
      description: null
      expression: "CASE \n  WHEN jed >= date_trunc('year', current_date) \n      \
        \ AND jed < date_trunc('year', current_date + interval '1 year') \n  THEN\
        \ cbm\n  ELSE 0 \nEND\n"
      filterable: true
      groupby: true
      id: 4408
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: CBM This Year
    optionName: metric_gi4ulnc8hf8_dk6x4dyo41
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: CBM Last Year
      description: null
      expression: "CASE \n  WHEN jed >= date_trunc('year', current_date - interval\
        \ '1 year') \n       AND jed < date_trunc('year', current_date) \n  THEN cbm\n\
        \  ELSE 0 \nEND\n"
      filterable: true
      groupby: true
      id: 4407
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: CBM Prev Year
    optionName: metric_bxf75ehejk_5x9454a0sfs
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: CBM Difference
      description: null
      expression: "CASE \n  WHEN jed >= date_trunc('year', current_date) \n      \
        \ AND jed < date_trunc('year', current_date + interval '1 year') \n  THEN\
        \ cbm\n  ELSE 0 \nEND\n-\nCASE \n  WHEN jed >= date_trunc('year', current_date\
        \ - interval '1 year') \n       AND jed < date_trunc('year', current_date)\
        \ \n  THEN cbm\n  ELSE 0 \nEND"
      filterable: true
      groupby: true
      id: 4406
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: CBM Growth
    optionName: metric_b6t58ivjz6e_qmhstt333f
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_70g9tvgxako_zngw5oocq0h
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_mvttpb01g69_8yitlwcp9tj
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_kd08happbji_yog9u829g1d
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  comparison_type: values
  metrics_b:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: CBM Difference
      description: null
      expression: "CASE \n  WHEN jed >= date_trunc('year', current_date) \n      \
        \ AND jed < date_trunc('year', current_date + interval '1 year') \n  THEN\
        \ cbm\n  ELSE 0 \nEND\n-\nCASE \n  WHEN jed >= date_trunc('year', current_date\
        \ - interval '1 year') \n       AND jed < date_trunc('year', current_date)\
        \ \n  THEN cbm\n  ELSE 0 \nEND"
      filterable: true
      groupby: true
      id: 4406
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: CBM Growth
    optionName: metric_x861p2pkgad_lzb48lrni4
  groupby_b: []
  adhoc_filters_b:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_gzsm31d3eq_30eag4ktwe7
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_cagk4qca9sk_7xoxjwlwq46
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_9wib7t3jd5o_ih8b1pjpf9m
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  order_desc_b: true
  row_limit_b: 10000
  truncate_metric_b: true
  comparison_type_b: values
  annotation_layers: []
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: shipmnts_colors
  seriesType: bar
  opacity: 0.2
  markerSize: 6
  seriesTypeB: line
  opacityB: 0.2
  markerSizeB: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_bounds_secondary:
  - null
  - null
  y_axis_format_secondary: SMART_NUMBER
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":79,"type":"table"},"force":false,"queries":[{"filters":[{"col":"jed","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"trade","op":"IN","val":["export"]},{"col":"freight","op":"IN","val":["ocean"]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"JED
  Month (Numeric)","label":"JED Month (Numeric)","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  This Year","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date) \n       AND jed < date_trunc(''year'', current_date + interval ''1
  year'') \n  THEN cbm\n  ELSE 0 \nEND\n","filterable":true,"groupby":true,"id":4408,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  This Year","optionName":"metric_gi4ulnc8hf8_dk6x4dyo41"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  Last Year","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date - interval ''1 year'') \n       AND jed < date_trunc(''year'', current_date)
  \n  THEN cbm\n  ELSE 0 \nEND\n","filterable":true,"groupby":true,"id":4407,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  Prev Year","optionName":"metric_bxf75ehejk_5x9454a0sfs"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  Difference","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date) \n       AND jed < date_trunc(''year'', current_date + interval ''1
  year'') \n  THEN cbm\n  ELSE 0 \nEND\n-\nCASE \n  WHEN jed >= date_trunc(''year'',
  current_date - interval ''1 year'') \n       AND jed < date_trunc(''year'', current_date)
  \n  THEN cbm\n  ELSE 0 \nEND","filterable":true,"groupby":true,"id":4406,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  Growth","optionName":"metric_b6t58ivjz6e_qmhstt333f"}],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["JED
  Month (Numeric)"],"columns":[],"aggregates":{"CBM This Year":{"operator":"mean"},"CBM
  Prev Year":{"operator":"mean"},"CBM Growth":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  This Year","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date) \n       AND jed < date_trunc(''year'', current_date + interval ''1
  year'') \n  THEN cbm\n  ELSE 0 \nEND\n","filterable":true,"groupby":true,"id":4408,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  This Year","optionName":"metric_gi4ulnc8hf8_dk6x4dyo41"},false]]},{"filters":[{"col":"jed","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"trade","op":"IN","val":["export"]},{"col":"freight","op":"IN","val":["ocean"]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"JED
  Month (Numeric)","label":"JED Month (Numeric)","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  Difference","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date) \n       AND jed < date_trunc(''year'', current_date + interval ''1
  year'') \n  THEN cbm\n  ELSE 0 \nEND\n-\nCASE \n  WHEN jed >= date_trunc(''year'',
  current_date - interval ''1 year'') \n       AND jed < date_trunc(''year'', current_date)
  \n  THEN cbm\n  ELSE 0 \nEND","filterable":true,"groupby":true,"id":4406,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  Growth","optionName":"metric_x861p2pkgad_lzb48lrni4"}],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["JED
  Month (Numeric)"],"columns":[],"aggregates":{"CBM Growth":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  Difference","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date) \n       AND jed < date_trunc(''year'', current_date + interval ''1
  year'') \n  THEN cbm\n  ELSE 0 \nEND\n-\nCASE \n  WHEN jed >= date_trunc(''year'',
  current_date - interval ''1 year'') \n       AND jed < date_trunc(''year'', current_date)
  \n  THEN cbm\n  ELSE 0 \nEND","filterable":true,"groupby":true,"id":4406,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  Growth","optionName":"metric_x861p2pkgad_lzb48lrni4"},false]]}],"form_data":{"datasource":"79__table","viz_type":"mixed_timeseries","slice_id":976,"x_axis":"JED
  Month (Numeric)","metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  This Year","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date) \n       AND jed < date_trunc(''year'', current_date + interval ''1
  year'') \n  THEN cbm\n  ELSE 0 \nEND\n","filterable":true,"groupby":true,"id":4408,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  This Year","optionName":"metric_gi4ulnc8hf8_dk6x4dyo41"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  Last Year","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date - interval ''1 year'') \n       AND jed < date_trunc(''year'', current_date)
  \n  THEN cbm\n  ELSE 0 \nEND\n","filterable":true,"groupby":true,"id":4407,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  Prev Year","optionName":"metric_bxf75ehejk_5x9454a0sfs"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"CBM
  Difference","description":null,"expression":"CASE \n  WHEN jed >= date_trunc(''year'',
  current_date) \n       AND jed < date_trunc(''year'', current_date + interval ''1
  year'') \n  THEN cbm\n  ELSE 0 \nEND\n-\nCASE \n  WHEN jed >= date_trunc(''year'',
  current_date - interval ''1 year'') \n       AND jed < date_trunc(''year'', current_date)
  \n  THEN cbm\n  ELSE 0 \nEND","filterable":true,"groupby":true,"id":4406,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"CBM
  Growth","optionName":"metric_b6t58ivjz6e_qmhstt333f"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_70g9tvgxako_zngw5oocq0h","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"jed"},{"clause":"WHERE","comparator":["export"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_mvttpb01g69_8yitlwcp9tj","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"trade"},{"clause":"WHERE","comparator":["ocean"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_kd08happbji_yog9u829g1d","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"freight"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"comparison_type":"values","annotation_layers":[],"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","color_scheme":"shipmnts_colors","seriesType":"bar","opacity":0.2,"markerSize":6,"seriesTypeB":"line","opacityB":0.2,"markerSizeB":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","truncateXAxis":true,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","y_axis_bounds_secondary":[null,null],"y_axis_format_secondary":"SMART_NUMBER","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 1731d214-3a37-4c7b-bab9-4246bad926c8
version: 1.0.0
dataset_uuid: 1796121c-92ed-4c17-bbdc-0169cf3c1c17
