slice_name: Month on Month TEU Trend - OE
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 70__table
  viz_type: echarts_timeseries_bar
  slice_id: 856
  x_axis: jed
  time_grain_sqla: P1M
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: teu_count
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 3077
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: TEUs
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: TEUs
    optionName: metric_lwh2wa3yaep_oz6ypkrrtg8
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator:
    - fcl
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_aao4uxuxnov_elkguld6ok
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: load_type
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_3vy90gatchq_wk3m7pu6sv
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_50dwddsumbf_4jhl2sf08gq
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator: Last year
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_nozuco43g3n_gpzrjshkf1o
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: d3Category20c
  show_value: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 64
query_context: null
cache_timeout: null
uuid: 3a23318b-e099-485e-a7ae-ee0c5a90c12e
version: 1.0.0
dataset_uuid: 1796121c-92ed-4c17-bbdc-0169cf3c1c17
