slice_name: Month on Month TAT of Direct BL Released
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 12__table
  viz_type: echarts_timeseries_bar
  slice_id: 951
  x_axis: Given / Surrendered
  time_grain_sqla: P1M
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Customer release TAT
      description: null
      expression: CASE WHEN given_to_customer_at is NOT NULL THEN given_to_customer_at-carrier_released
        ELSE surrendered_at_origin_at-carrier_released END
      filterable: true
      groupby: true
      id: 2931
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Customer Release TAT
    optionName: metric_begern2p9b4_zc323xmrirj
  groupby:
  - MBL Customer Release - On Time / Delayed
  adhoc_filters:
  - clause: WHERE
    comparator:
    - direct
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_4ha0ps3yc3u_6y37mjh8zqb
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: ship_type
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_3dsigyc91so_kwek5mbj61
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: carrier_released is not NULL
    subject: null
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_k8ush1w5s59_l1j3vf18wn
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: job_number is not NULL
    subject: null
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_sr3rc8l2es_epdu40uxr9o
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: (given_to_customer_at is not NULL or surrendered_at_origin_at is
      not NULL)
    subject: null
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_8vwk96zgn9y_bzfqqjcc28
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: Given / Surrendered
  order_desc: true
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: shipmnts_colors
  stack: Stack
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":12,"type":"table"},"force":false,"queries":[{"filters":[{"col":"ship_type","op":"IN","val":["direct"]},{"col":"Given
  / Surrendered","op":"TEMPORAL_RANGE","val":"No filter"}],"extras":{"time_grain_sqla":"P1M","having":"","where":"(carrier_released
  is not NULL) AND (job_number is not NULL) AND ((given_to_customer_at is not NULL
  or surrendered_at_origin_at is not NULL))"},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"Given
  / Surrendered","label":"Given / Surrendered","expressionType":"SQL"},"MBL Customer
  Release - On Time / Delayed"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Customer
  release TAT","description":null,"expression":"CASE WHEN given_to_customer_at is
  NOT NULL THEN given_to_customer_at-carrier_released ELSE surrendered_at_origin_at-carrier_released
  END","filterable":true,"groupby":true,"id":2931,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Customer
  Release TAT","optionName":"metric_begern2p9b4_zc323xmrirj"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Customer
  release TAT","description":null,"expression":"CASE WHEN given_to_customer_at is
  NOT NULL THEN given_to_customer_at-carrier_released ELSE surrendered_at_origin_at-carrier_released
  END","filterable":true,"groupby":true,"id":2931,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Customer
  Release TAT","optionName":"metric_begern2p9b4_zc323xmrirj"},false]],"annotation_layers":[],"row_limit":1000,"series_columns":["MBL
  Customer Release - On Time / Delayed"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["Given
  / Surrendered"],"columns":["MBL Customer Release - On Time / Delayed"],"aggregates":{"Customer
  Release TAT":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"Customer
  Release TAT":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"12__table","viz_type":"echarts_timeseries_bar","slice_id":951,"x_axis":"Given
  / Surrendered","time_grain_sqla":"P1M","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Customer
  release TAT","description":null,"expression":"CASE WHEN given_to_customer_at is
  NOT NULL THEN given_to_customer_at-carrier_released ELSE surrendered_at_origin_at-carrier_released
  END","filterable":true,"groupby":true,"id":2931,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Customer
  Release TAT","optionName":"metric_begern2p9b4_zc323xmrirj"}],"groupby":["MBL Customer
  Release - On Time / Delayed"],"adhoc_filters":[{"clause":"WHERE","comparator":["direct"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_4ha0ps3yc3u_6y37mjh8zqb","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"ship_type"},{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_3dsigyc91so_kwek5mbj61","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"carrier_released
  is not NULL","subject":null},{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_k8ush1w5s59_l1j3vf18wn","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"job_number
  is not NULL","subject":null},{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_sr3rc8l2es_epdu40uxr9o","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"(given_to_customer_at
  is not NULL or surrendered_at_origin_at is not NULL)","subject":null},{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_8vwk96zgn9y_bzfqqjcc28","isExtra":true,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"Given
  / Surrendered"}],"order_desc":true,"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"shipmnts_colors","stack":"Stack","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: e6e3927b-50ab-413e-82de-b948b09e24d4
version: 1.0.0
dataset_uuid: 4fc51f9b-3504-4494-9dde-c1ff47aec07c
