slice_name: Month on Month Volume Trend - Air Export Forwarding
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 79__table
  viz_type: echarts_timeseries_bar
  slice_id: 996
  x_axis: JED Month (Numeric)
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - count
  - expressionType: SQL
    sqlExpression: SUM(tonnage/1000)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Tonnage
    optionName: metric_jyfpiafahf_gg3frqdg7vs
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_l4mwztgdzx_7p3afdaez6t
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator:
    - '1'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_6s5vukoo2xr_m0nwb5oh39s
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: is_forwarding
  - clause: WHERE
    comparator:
    - air
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_gnm2k3il2hh_xhvwc5oa54f
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_nozuco43g3n_gpzrjshkf1o
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: d3Category20c
  show_value: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 67
query_context: '{"datasource":{"id":79,"type":"table"},"force":false,"queries":[{"filters":[{"col":"trade","op":"IN","val":["export"]},{"col":"is_forwarding","op":"IN","val":["1"]},{"col":"freight","op":"IN","val":["air"]},{"col":"jed","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"JED
  Month (Numeric)","label":"JED Month (Numeric)","expressionType":"SQL"}],"metrics":["count",{"expressionType":"SQL","sqlExpression":"SUM(tonnage/1000)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Tonnage","optionName":"metric_jyfpiafahf_gg3frqdg7vs"}],"orderby":[["count",false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["JED
  Month (Numeric)"],"columns":[],"aggregates":{"count":{"operator":"mean"},"Tonnage":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"79__table","viz_type":"echarts_timeseries_bar","slice_id":996,"x_axis":"JED
  Month (Numeric)","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":["count",{"expressionType":"SQL","sqlExpression":"SUM(tonnage/1000)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Tonnage","optionName":"metric_jyfpiafahf_gg3frqdg7vs"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":["export"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_l4mwztgdzx_7p3afdaez6t","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"trade"},{"clause":"WHERE","comparator":["1"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_6s5vukoo2xr_m0nwb5oh39s","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"is_forwarding"},{"clause":"WHERE","comparator":["air"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_gnm2k3il2hh_xhvwc5oa54f","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"freight"},{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_nozuco43g3n_gpzrjshkf1o","isExtra":true,"isNew":false,"operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","sqlExpression":null,"subject":"jed"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"d3Category20c","show_value":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"bottom","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","logAxis":false,"truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[67],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 02132519-2324-46e7-9d59-6ff2d4fa974f
version: 1.0.0
dataset_uuid: 1796121c-92ed-4c17-bbdc-0169cf3c1c17
