slice_name: Month on Month Volume Trend - Ocean Import Forwarding
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 79__table
  viz_type: echarts_timeseries_bar
  slice_id: 993
  x_axis: JED Month (Numeric)
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: teu_count
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 3077
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: TEUs
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: TEUs
    optionName: metric_8ndqnuf2uyi_z3v3apd5vxa
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: cbm
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 3088
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: CBM
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: CBM
    optionName: metric_c1ulj8ion2u_orw337d0fb
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: trade
    operator: IN
    operatorId: IN
    comparator:
    - import
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_l4mwztgdzx_7p3afdaez6t
  - expressionType: SIMPLE
    subject: is_forwarding
    operator: IN
    operatorId: IN
    comparator:
    - '1'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_6s5vukoo2xr_m0nwb5oh39s
  - expressionType: SIMPLE
    subject: jed
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_nozuco43g3n_gpzrjshkf1o
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: d3Category20c
  show_value: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":79,"type":"table"},"force":false,"queries":[{"filters":[{"col":"trade","op":"IN","val":["import"]},{"col":"is_forwarding","op":"IN","val":["1"]},{"col":"jed","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"JED
  Month (Numeric)","label":"JED Month (Numeric)","expressionType":"SQL"}],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"teu_count","description":null,"expression":"","filterable":true,"groupby":true,"id":3077,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":"TEUs","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"TEUs","optionName":"metric_8ndqnuf2uyi_z3v3apd5vxa","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"cbm","description":null,"expression":"","filterable":true,"groupby":true,"id":3088,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"CBM","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"CBM","optionName":"metric_c1ulj8ion2u_orw337d0fb","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"teu_count","description":null,"expression":"","filterable":true,"groupby":true,"id":3077,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":"TEUs","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"TEUs","optionName":"metric_8ndqnuf2uyi_z3v3apd5vxa","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["JED
  Month (Numeric)"],"columns":[],"aggregates":{"TEUs":{"operator":"mean"},"CBM":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"79__table","viz_type":"echarts_timeseries_bar","slice_id":993,"x_axis":"JED
  Month (Numeric)","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"teu_count","description":null,"expression":"","filterable":true,"groupby":true,"id":3077,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":"TEUs","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"TEUs","optionName":"metric_8ndqnuf2uyi_z3v3apd5vxa","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"cbm","description":null,"expression":"","filterable":true,"groupby":true,"id":3088,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"CBM","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"CBM","optionName":"metric_c1ulj8ion2u_orw337d0fb","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"trade","operator":"IN","operatorId":"IN","comparator":["import"],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_l4mwztgdzx_7p3afdaez6t"},{"expressionType":"SIMPLE","subject":"is_forwarding","operator":"IN","operatorId":"IN","comparator":["1"],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_6s5vukoo2xr_m0nwb5oh39s"},{"expressionType":"SIMPLE","subject":"jed","operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":true,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_nozuco43g3n_gpzrjshkf1o"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"d3Category20c","show_value":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"bottom","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","logAxis":false,"truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: b4e211df-1a79-472d-892c-0474bce36536
version: 1.0.0
dataset_uuid: 1796121c-92ed-4c17-bbdc-0169cf3c1c17
