slice_name: Ocean Carrier wise Revenue and GP Trend - Month on Month
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 9__table
  viz_type: pivot_table_v2
  slice_id: 412
  groupbyColumns:
  - JED Week
  groupbyRows:
  - carrier
  - business_vertical
  temporal_columns_lookup:
    jed: true
    job_close_date: true
    onboarded_on: true
    customer_created_at: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: estimated_gp
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4395
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: Estimated GP
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Estimated GP
    optionName: metric_kn9fdqgjkc_bdfu1w7u50h
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: actual_gp
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4394
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: Actual GP
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Actual GP
    optionName: metric_69a872j8b9q_2l6lksjsk79
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: estimate_income
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4383
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: Estimated Income
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Estimated Income
    optionName: metric_p8lpn8xl6kd_lpcpoqcsjni
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: actual_income
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4380
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: Actual Income
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Income
    optionName: metric_rqx6ltm7nxf_w6k9gwita1e
    sqlExpression: null
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_vi517a3jtsr_tyk4xch0wnq
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_jb14g7qfhb_3fmnfhvz3cx
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  expandCollapse: true
  colTotals: true
  combineMetric: true
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: value_z_to_a
  colOrder: key_z_to_a
  conditional_formatting:
  - colorScheme: '#E0F0FF'
    column: Income
    operator: None
  - colorScheme: '#F0F5FF'
    column: Estimated Income
    operator: None
  - colorScheme: '#E6FFFB'
    column: Actual GP
    operator: None
  - colorScheme: '#E8EBFE'
    column: Estimated GP
    operator: None
  - colorScheme: '#CDFEE1'
    column: Deviation %
    operator: '>'
    targetValue: 0
  - colorScheme: '#FEDAD9'
    column: Deviation %
    operator: <
    targetValue: 0
  extra_form_data: {}
  dashboards:
  - 4
  - 67
query_context: '{"datasource":{"id":9,"type":"table"},"force":false,"queries":[{"filters":[{"col":"freight","op":"IN","val":["ocean"]},{"col":"jed","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["JED
  Week","carrier","business_vertical"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"estimated_gp","description":null,"expression":null,"filterable":true,"groupby":true,"id":4395,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Estimated
  GP","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Estimated
  GP","optionName":"metric_kn9fdqgjkc_bdfu1w7u50h","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"actual_gp","description":null,"expression":null,"filterable":true,"groupby":true,"id":4394,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Actual
  GP","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Actual
  GP","optionName":"metric_69a872j8b9q_2l6lksjsk79","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"estimate_income","description":null,"expression":null,"filterable":true,"groupby":true,"id":4383,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Estimated
  Income","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Estimated
  Income","optionName":"metric_p8lpn8xl6kd_lpcpoqcsjni","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"actual_income","description":null,"expression":null,"filterable":true,"groupby":true,"id":4380,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Actual
  Income","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Income","optionName":"metric_rqx6ltm7nxf_w6k9gwita1e","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"estimated_gp","description":null,"expression":null,"filterable":true,"groupby":true,"id":4395,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Estimated
  GP","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Estimated
  GP","optionName":"metric_kn9fdqgjkc_bdfu1w7u50h","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"9__table","viz_type":"pivot_table_v2","slice_id":412,"groupbyColumns":["JED
  Week"],"groupbyRows":["carrier","business_vertical"],"temporal_columns_lookup":{"jed":true,"job_close_date":true,"onboarded_on":true,"customer_created_at":true},"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"estimated_gp","description":null,"expression":null,"filterable":true,"groupby":true,"id":4395,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Estimated
  GP","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Estimated
  GP","optionName":"metric_kn9fdqgjkc_bdfu1w7u50h","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"actual_gp","description":null,"expression":null,"filterable":true,"groupby":true,"id":4394,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Actual
  GP","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Actual
  GP","optionName":"metric_69a872j8b9q_2l6lksjsk79","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"estimate_income","description":null,"expression":null,"filterable":true,"groupby":true,"id":4383,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Estimated
  Income","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Estimated
  Income","optionName":"metric_p8lpn8xl6kd_lpcpoqcsjni","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"actual_income","description":null,"expression":null,"filterable":true,"groupby":true,"id":4380,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":"Actual
  Income","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Income","optionName":"metric_rqx6ltm7nxf_w6k9gwita1e","sqlExpression":null}],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":["ocean"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_vi517a3jtsr_tyk4xch0wnq","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"freight"},{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_jb14g7qfhb_3fmnfhvz3cx","isExtra":true,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"jed"}],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","expandCollapse":true,"colTotals":true,"combineMetric":true,"valueFormat":"SMART_NUMBER","date_format":"smart_date","rowOrder":"value_z_to_a","colOrder":"key_z_to_a","conditional_formatting":[{"colorScheme":"#E0F0FF","column":"Income","operator":"None"},{"colorScheme":"#F0F5FF","column":"Estimated
  Income","operator":"None"},{"colorScheme":"#E6FFFB","column":"Actual GP","operator":"None"},{"colorScheme":"#E8EBFE","column":"Estimated
  GP","operator":"None"},{"colorScheme":"#CDFEE1","column":"Deviation %","operator":">","targetValue":0},{"colorScheme":"#FEDAD9","column":"Deviation
  %","operator":"<","targetValue":0}],"extra_form_data":{},"dashboards":[4,67],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fcd6dfe2-36b5-4b73-b05f-8cbe58c13f33
version: 1.0.0
dataset_uuid: ed854b24-dc83-420a-b942-0ac77d1d6be1
