slice_name: Overdue Payable OS
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 106__table
  viz_type: big_number
  slice_id: 316
  x_axis: posting_date
  time_grain_sqla: P1M
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2024-11-17T08:27:00.867245'
      column_name: Overdue Amount
      created_on: '2024-11-17T08:27:00.867240'
      description: null
      expression: "CASE \n    WHEN CURDATE() > due_date THEN net_os\n    ELSE 0\n\
        END"
      extra: '{}'
      filterable: true
      groupby: true
      id: 2050
      is_active: true
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      uuid: c8ad8c91-a763-44b3-a06e-386e81d6f7f5
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(Overdue Amount)
    optionName: metric_sskpl5evnnh_49gzm8gn51a
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: posting_date
  compare_lag: 1
  show_trend_line: false
  start_y_axis_at_zero: true
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  header_font_size: 0.6
  subheader_font_size: 0.4
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: cumsum
  extra_form_data: {}
  dashboards:
  - 20
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 4df5e87f-7feb-4b75-a6a9-98aef962a7d0
version: 1.0.0
dataset_uuid: f5bead0e-a014-48fa-80b2-86e1403f8380
