slice_name: Payable within Due
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 106__table
  viz_type: big_number
  slice_id: 317
  x_axis: posting_date
  time_grain_sqla: P1M
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      changed_on: '2024-11-17T10:47:51.406678'
      column_name: O/S Within Due
      created_on: '2024-11-17T10:47:51.406672'
      description: null
      expression: "CASE \n    WHEN CURDATE() <= due_date THEN net_os\n    ELSE 0\n\
        END"
      extra: '{}'
      filterable: true
      groupby: true
      id: 2054
      is_active: true
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      uuid: 993a8bc2-1a57-4cdf-b973-a9f1142d3fa1
      verbose_name: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Net Payable
    optionName: metric_o9ekpo2asis_xq5x9mdamsm
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ecc1algt13d_8c5oy3kl1xm
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: posting_date
  - clause: WHERE
    comparator:
    - Purchase Invoice
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_803y8edr758_kdizp5ot2j
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: real_voucher_type
  compare_lag: 1
  show_trend_line: false
  start_y_axis_at_zero: true
  color_picker:
    r: 0
    g: 122
    b: 135
    a: 1
  header_font_size: 0.6
  subheader_font_size: 0.4
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: cumsum
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 42308092-5009-4e6f-9d41-dba878ba1c50
version: 1.0.0
dataset_uuid: f5bead0e-a014-48fa-80b2-86e1403f8380
