slice_name: Payment Trend
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 108__table
  viz_type: echarts_timeseries_bar
  slice_id: 328
  x_axis: payment_date
  time_grain_sqla: P1M
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: payment_amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2043
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NEWDECIMAL
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Payment Amount
    optionName: metric_ezrye9f2bth_wa59sf15wr
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: Last year
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ifyg1v9lls_lnfnkfc9dvm
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: payment_date
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  rolling_type: cumsum
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: d3Category20
  show_value: false
  only_total: true
  show_legend: false
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 20
query_context: null
cache_timeout: null
uuid: e0319a9b-45cb-42c2-857f-fdcabd7725eb
version: 1.0.0
dataset_uuid: e8f64336-0ac8-44fd-8cba-a5d86f83a471
