slice_name: Quoted Tonnage- Won
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 88__table
  viz_type: big_number
  slice_id: 310
  x_axis: created_at
  time_grain_sqla: P1M
  metric:
    expressionType: SQL
    sqlExpression: SUM(total_gross_weight)/1000
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Tonnage
    optionName: metric_3h61r34ztpd_ywhyu0pfj1
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_sv8rs2vymvc_8qyktfw0g4x
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: created_at
  - clause: WHERE
    comparator:
    - won
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_x93xnptdzqk_vfom68wgl3
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: quote_status
  compare_lag: 1
  show_trend_line: false
  start_y_axis_at_zero: true
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  header_font_size: 0.6
  subheader_font_size: 0.4
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: None
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 0bdb63f3-6dd6-4146-bb6c-5b3db4becc2c
version: 1.0.0
dataset_uuid: 3f348298-40e0-4d14-99b3-efe47f94b006
