slice_name: Quoted TEUs - Won
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 88__table
  viz_type: big_number
  slice_id: 308
  x_axis: created_at
  time_grain_sqla: P1M
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: teus
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 729
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: TEUs
    optionName: metric_3h61r34ztpd_ywhyu0pfj1
  adhoc_filters:
  - expressionType: SIMPLE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_sv8rs2vymvc_8qyktfw0g4x
  - expressionType: SIMPLE
    subject: quote_status
    operator: IN
    operatorId: IN
    comparator:
    - won
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_x93xnptdzqk_vfom68wgl3
  compare_lag: 1
  show_trend_line: false
  start_y_axis_at_zero: true
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  header_font_size: 0.6
  subheader_font_size: 0.4
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: None
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 936d774b-669e-4ea8-ab2f-1fca0f08938c
version: 1.0.0
dataset_uuid: 3f348298-40e0-4d14-99b3-efe47f94b006
