slice_name: Sales Person Wise TEU Growth % Compared to Prev Year - OE
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 79__table
  viz_type: pivot_table_v2
  slice_id: 877
  groupbyColumns:
  - JED Month (Numeric)
  groupbyRows:
  - sales_person
  time_grain_sqla: P1D
  temporal_columns_lookup:
    job_date: true
    si_cutoff: true
    onboared: true
    last_shipment: true
    last_inquiry: true
    jed: true
    created: true
  metrics:
  - TEU YoY Growth %
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_kvj3w68ylb_l77gmas433e
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_0stw08kynstl_115m9ose376e
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ff8joyg0n5w_mrqne9lukb
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  colTotals: true
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting:
  - column: TEU YoY Growth %
    colorScheme: '#FEDAD9'
    operator: "\u2264"
    targetValue: 0
  - column: TEU YoY Growth %
    colorScheme: '#CDFEE1'
    operator: '>'
    targetValue: 0
  extra_form_data: {}
  dashboards: []
query_context: "{\"datasource\":{\"id\":79,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"jed\",\"op\":\"TEMPORAL_RANGE\",\"val\":\"No\
  \ filter\"},{\"col\":\"trade\",\"op\":\"IN\",\"val\":[\"export\"]},{\"col\":\"freight\"\
  ,\"op\":\"IN\",\"val\":[\"ocean\"]}],\"extras\":{\"time_grain_sqla\":\"P1D\",\"\
  having\":\"\",\"where\":\"\"},\"applied_time_extras\":{},\"columns\":[\"JED Month\
  \ (Numeric)\",\"sales_person\"],\"metrics\":[\"TEU YoY Growth %\"],\"orderby\":[[\"\
  TEU YoY Growth %\",false]],\"annotation_layers\":[],\"row_limit\":10000,\"series_limit\"\
  :0,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{}}],\"form_data\":{\"datasource\":\"79__table\",\"viz_type\":\"pivot_table_v2\"\
  ,\"slice_id\":877,\"groupbyColumns\":[\"JED Month (Numeric)\"],\"groupbyRows\":[\"\
  sales_person\"],\"time_grain_sqla\":\"P1D\",\"temporal_columns_lookup\":{\"job_date\"\
  :true,\"si_cutoff\":true,\"onboared\":true,\"last_shipment\":true,\"last_inquiry\"\
  :true,\"jed\":true,\"created\":true},\"metrics\":[\"TEU YoY Growth %\"],\"metricsLayout\"\
  :\"COLUMNS\",\"adhoc_filters\":[{\"clause\":\"WHERE\",\"comparator\":\"No filter\"\
  ,\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"filterOptionName\"\
  :\"filter_kvj3w68ylb_l77gmas433e\",\"isExtra\":false,\"isNew\":false,\"operator\"\
  :\"TEMPORAL_RANGE\",\"sqlExpression\":null,\"subject\":\"jed\"},{\"clause\":\"WHERE\"\
  ,\"comparator\":[\"export\"],\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\"\
  ,\"filterOptionName\":\"filter_0stw08kynstl_115m9ose376e\",\"isExtra\":false,\"\
  isNew\":false,\"operator\":\"IN\",\"operatorId\":\"IN\",\"sqlExpression\":null,\"\
  subject\":\"trade\"},{\"clause\":\"WHERE\",\"comparator\":[\"ocean\"],\"datasourceWarning\"\
  :false,\"expressionType\":\"SIMPLE\",\"filterOptionName\":\"filter_ff8joyg0n5w_mrqne9lukb\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":\"IN\",\"operatorId\":\"IN\",\"\
  sqlExpression\":null,\"subject\":\"freight\"}],\"row_limit\":10000,\"order_desc\"\
  :true,\"aggregateFunction\":\"Sum\",\"colTotals\":true,\"valueFormat\":\"SMART_NUMBER\"\
  ,\"date_format\":\"smart_date\",\"rowOrder\":\"key_a_to_z\",\"colOrder\":\"key_a_to_z\"\
  ,\"conditional_formatting\":[{\"column\":\"TEU YoY Growth %\",\"colorScheme\":\"\
  #FEDAD9\",\"operator\":\"\u2264\",\"targetValue\":0},{\"column\":\"TEU YoY Growth\
  \ %\",\"colorScheme\":\"#CDFEE1\",\"operator\":\">\",\"targetValue\":0}],\"extra_form_data\"\
  :{},\"dashboards\":[],\"force\":false,\"result_format\":\"json\",\"result_type\"\
  :\"full\"},\"result_format\":\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 21cebc50-e648-42b0-a0df-90b5fbd4facf
version: 1.0.0
dataset_uuid: 1796121c-92ed-4c17-bbdc-0169cf3c1c17
