slice_name: Sales Person Wise Volume Trend - Week on Week
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 79__table
  viz_type: pivot_table_v2
  slice_id: 29
  groupbyColumns:
  - JED Week with year
  groupbyRows:
  - sales_person
  temporal_columns_lookup:
    jed: true
    created: true
    job_date: true
    si_cutoff: true
    onboared: true
    last_shipment: true
    last_inquiry: true
  metrics:
  - count
  - FCL TEU
  - Tonnage
  - LCL CBM
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_hircf178fhi_eurb775k41t
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_dcxdc8scj1g_im928l64b
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  row_limit: 10000
  series_limit_metric:
    aggregate: MAX
    column:
      advanced_data_type: null
      changed_on: '2024-08-26T13:09:41.709277'
      column_name: jed
      created_on: '2024-08-26T13:09:41.296832'
      description: null
      expression: ''
      extra: '{"warning_markdown":null}'
      filterable: true
      groupby: true
      id: 361
      is_active: true
      is_dttm: true
      python_date_format: null
      type: DATE
      type_generic: 2
      uuid: 63f7a230-7a7f-4990-89a3-ffda961c2a8a
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(jed)
    optionName: metric_2rlqp5dcbwp_5bipmhgpxsw
    sqlExpression: null
  order_desc: true
  aggregateFunction: Sum
  rowTotals: false
  rowSubTotals: false
  colTotals: true
  colSubTotals: false
  combineMetric: true
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: value_z_to_a
  colOrder: key_z_to_a
  conditional_formatting:
  - colorScheme: '#E0F0FF'
    column: Tonnage
    operator: None
  - colorScheme: '#E6FFFB'
    column: count
    operator: None
  - colorScheme: '#F0F5FF'
    column: LCL CBM
    operator: None
  - colorScheme: '#D6E4FF'
    column: FCL TEU
    operator: None
  extra_form_data: {}
  dashboards:
  - 4
query_context: '{"datasource":{"id":79,"type":"table"},"force":false,"queries":[{"filters":[{"col":"jed","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"jed","op":"TEMPORAL_RANGE","val":"No filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["JED
  Week with year","sales_person"],"metrics":["count","FCL TEU","Tonnage","LCL CBM"],"orderby":[[{"aggregate":"MAX","column":{"advanced_data_type":null,"changed_on":"2024-08-26T13:09:41.709277","column_name":"jed","created_on":"2024-08-26T13:09:41.296832","description":null,"expression":"","extra":"{\"warning_markdown\":null}","filterable":true,"groupby":true,"id":361,"is_active":true,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"uuid":"63f7a230-7a7f-4990-89a3-ffda961c2a8a","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(jed)","optionName":"metric_2rlqp5dcbwp_5bipmhgpxsw","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"series_limit_metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"changed_on":"2024-08-26T13:09:41.709277","column_name":"jed","created_on":"2024-08-26T13:09:41.296832","description":null,"expression":"","extra":"{\"warning_markdown\":null}","filterable":true,"groupby":true,"id":361,"is_active":true,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"uuid":"63f7a230-7a7f-4990-89a3-ffda961c2a8a","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(jed)","optionName":"metric_2rlqp5dcbwp_5bipmhgpxsw","sqlExpression":null},"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"79__table","viz_type":"pivot_table_v2","slice_id":29,"groupbyColumns":["JED
  Week with year"],"groupbyRows":["sales_person"],"temporal_columns_lookup":{"jed":true,"created":true,"job_date":true,"si_cutoff":true,"onboared":true,"last_shipment":true,"last_inquiry":true},"metrics":["count","FCL
  TEU","Tonnage","LCL CBM"],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_hircf178fhi_eurb775k41t","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"jed"},{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_dcxdc8scj1g_im928l64b","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","sqlExpression":null,"subject":"jed"}],"row_limit":10000,"series_limit_metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"changed_on":"2024-08-26T13:09:41.709277","column_name":"jed","created_on":"2024-08-26T13:09:41.296832","description":null,"expression":"","extra":"{\"warning_markdown\":null}","filterable":true,"groupby":true,"id":361,"is_active":true,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"uuid":"63f7a230-7a7f-4990-89a3-ffda961c2a8a","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(jed)","optionName":"metric_2rlqp5dcbwp_5bipmhgpxsw","sqlExpression":null},"order_desc":true,"aggregateFunction":"Sum","rowTotals":false,"rowSubTotals":false,"colTotals":true,"colSubTotals":false,"combineMetric":true,"valueFormat":"SMART_NUMBER","date_format":"smart_date","rowOrder":"value_z_to_a","colOrder":"key_z_to_a","conditional_formatting":[{"colorScheme":"#E0F0FF","column":"Tonnage","operator":"None"},{"colorScheme":"#E6FFFB","column":"count","operator":"None"},{"colorScheme":"#F0F5FF","column":"LCL
  CBM","operator":"None"},{"colorScheme":"#D6E4FF","column":"FCL TEU","operator":"None"}],"extra_form_data":{},"dashboards":[4],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 0cc6c97d-43d7-476c-9ec5-c6cacb4d4cce
version: 1.0.0
dataset_uuid: 1796121c-92ed-4c17-bbdc-0169cf3c1c17
