slice_name: Sales Wise Comparisons of Revenue from Prev Period - Overall
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 9__table
  viz_type: pivot_table_v2
  slice_id: 878
  groupbyColumns: []
  groupbyRows:
  - sales_person
  - business_vertical
  temporal_columns_lookup:
    jed: true
    job_close_date: true
    onboarded_on: true
    customer_created_at: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Revenue This Week
      description: null
      expression: "CASE  \n    WHEN jed >= date_trunc('week', current_date)  \n  \
        \       AND jed < date_trunc('week', current_date + interval '1 week')  \n\
        \    THEN actual_income\n    ELSE 0  \n  END\n"
      filterable: true
      groupby: true
      id: 4323
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Revenue This Week
    optionName: metric_8lv4mlapql9_2d7vsiqbfjj
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Revenue Last Week
      description: null
      expression: "CASE  \n    WHEN jed >= date_trunc('week', current_date) - interval\
        \ '1 week'  \n    AND jed < date_trunc('week', current_date)  \n    THEN actual_income\n\
        \    ELSE 0  \nEND  \n"
      filterable: true
      groupby: true
      id: 4324
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Revenue Prev Week
    optionName: metric_9i9ll50p0da_2ur0ukck8f5
    sqlExpression: null
  - Weekly Avg Revenue
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Revenue MTD
      description: null
      expression: "CASE WHEN \njed >= date_trunc('month', current_date)\nAND jed <\
        \ current_date \nTHEN actual_income \nELSE 0 \nEND"
      filterable: true
      groupby: true
      id: 4322
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Revenue MTD
    optionName: metric_tc9ku7yakoh_nv9wfmyzy2p
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Revenue MTD - Prior
      description: null
      expression: "CASE WHEN jed >= date_trunc('month', current_date) - interval '1\
        \ year'\n              AND jed < date_trunc('month', current_date) - interval\
        \ '1 year' + (current_date - date_trunc('month', current_date)) \n       \
        \  THEN actual_income\n         ELSE 0 \n    END"
      filterable: true
      groupby: true
      id: 4321
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Revenue MTD Prev Year
    optionName: metric_968tmk1trxg_u1iobj3ns0m
    sqlExpression: null
  - Monthly Avg Revenue
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Revenue YTD - Current
      description: null
      expression: "CASE \n        WHEN jed >= date_trunc('year', current_date)\n \
        \            AND jed < current_date\n        THEN actual_income\n        ELSE\
        \ 0\n    END\n"
      filterable: true
      groupby: true
      id: 683
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Revenue YTD
    optionName: metric_a1amgf20y7_uf10zbeqxr
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Revenue YTD - Previous
      description: null
      expression: "CASE\n     WHEN jed >= date_trunc('year', current_date - interval\
        \ '1 year') \n             AND jed < (current_date - interval '1 year') \n\
        \    THEN actual_income\n    ELSE 0\nEND"
      filterable: true
      groupby: true
      id: 2180
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Revenue YTD Prev Year
    optionName: metric_30tefznun1_9uumtmd2yst
    sqlExpression: null
  metricsLayout: COLUMNS
  adhoc_filters:
  - expressionType: SIMPLE
    subject: jed
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_4qedl6zb4ze_6wlwjkefpij
  row_limit: '100000'
  order_desc: true
  aggregateFunction: Sum
  colTotals: true
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting:
  - column: Revenue This Week
    colorScheme: '#E8EBFE'
    operator: None
  - column: Revenue Prev Week
    colorScheme: '#E0F0FF'
    operator: None
  - column: Weekly Avg Revenue
    colorScheme: '#FFEF9D'
    operator: None
  - column: Revenue MTD
    colorScheme: '#E6FFFB'
    operator: None
  - column: Revenue MTD Prev Year
    colorScheme: '#87E8DE'
    operator: None
  - column: Monthly Avg Revenue
    colorScheme: '#EAFF8F'
    operator: None
  - column: Monthly Avg Revenue
    colorScheme: '#E0F0FF'
    operator: None
  - column: Revenue YTD Prev Year
    colorScheme: '#E8EBFE'
    operator: None
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":9,"type":"table"},"force":false,"queries":[{"filters":[{"col":"jed","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["sales_person","business_vertical"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  This Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date)  \n         AND jed < date_trunc(''week'', current_date + interval
  ''1 week'')  \n    THEN actual_income\n    ELSE 0  \n  END\n","filterable":true,"groupby":true,"id":4323,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  This Week","optionName":"metric_8lv4mlapql9_2d7vsiqbfjj","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  Last Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date) - interval ''1 week''  \n    AND jed < date_trunc(''week'', current_date)  \n    THEN
  actual_income\n    ELSE 0  \nEND  \n","filterable":true,"groupby":true,"id":4324,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  Prev Week","optionName":"metric_9i9ll50p0da_2ur0ukck8f5","sqlExpression":null},"Weekly
  Avg Revenue",{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  MTD","description":null,"expression":"CASE WHEN \njed >= date_trunc(''month'', current_date)\nAND
  jed < current_date \nTHEN actual_income \nELSE 0 \nEND","filterable":true,"groupby":true,"id":4322,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  MTD","optionName":"metric_tc9ku7yakoh_nv9wfmyzy2p","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  MTD - Prior","description":null,"expression":"CASE WHEN jed >= date_trunc(''month'',
  current_date) - interval ''1 year''\n              AND jed < date_trunc(''month'',
  current_date) - interval ''1 year'' + (current_date - date_trunc(''month'', current_date))
  \n         THEN actual_income\n         ELSE 0 \n    END","filterable":true,"groupby":true,"id":4321,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  MTD Prev Year","optionName":"metric_968tmk1trxg_u1iobj3ns0m","sqlExpression":null},"Monthly
  Avg Revenue",{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  YTD - Current","description":null,"expression":"CASE \n        WHEN jed >= date_trunc(''year'',
  current_date)\n             AND jed < current_date\n        THEN actual_income\n        ELSE
  0\n    END\n","filterable":true,"groupby":true,"id":683,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  YTD","optionName":"metric_a1amgf20y7_uf10zbeqxr","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  YTD - Previous","description":null,"expression":"CASE\n     WHEN jed >= date_trunc(''year'',
  current_date - interval ''1 year'') \n             AND jed < (current_date - interval
  ''1 year'') \n    THEN actual_income\n    ELSE 0\nEND","filterable":true,"groupby":true,"id":2180,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  YTD Prev Year","optionName":"metric_30tefznun1_9uumtmd2yst","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  This Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date)  \n         AND jed < date_trunc(''week'', current_date + interval
  ''1 week'')  \n    THEN actual_income\n    ELSE 0  \n  END\n","filterable":true,"groupby":true,"id":4323,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  This Week","optionName":"metric_8lv4mlapql9_2d7vsiqbfjj","sqlExpression":null},false]],"annotation_layers":[],"row_limit":100000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"9__table","viz_type":"pivot_table_v2","slice_id":878,"groupbyColumns":[],"groupbyRows":["sales_person","business_vertical"],"temporal_columns_lookup":{"jed":true,"job_close_date":true,"onboarded_on":true,"customer_created_at":true},"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  This Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date)  \n         AND jed < date_trunc(''week'', current_date + interval
  ''1 week'')  \n    THEN actual_income\n    ELSE 0  \n  END\n","filterable":true,"groupby":true,"id":4323,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  This Week","optionName":"metric_8lv4mlapql9_2d7vsiqbfjj","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  Last Week","description":null,"expression":"CASE  \n    WHEN jed >= date_trunc(''week'',
  current_date) - interval ''1 week''  \n    AND jed < date_trunc(''week'', current_date)  \n    THEN
  actual_income\n    ELSE 0  \nEND  \n","filterable":true,"groupby":true,"id":4324,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  Prev Week","optionName":"metric_9i9ll50p0da_2ur0ukck8f5","sqlExpression":null},"Weekly
  Avg Revenue",{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  MTD","description":null,"expression":"CASE WHEN \njed >= date_trunc(''month'', current_date)\nAND
  jed < current_date \nTHEN actual_income \nELSE 0 \nEND","filterable":true,"groupby":true,"id":4322,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  MTD","optionName":"metric_tc9ku7yakoh_nv9wfmyzy2p","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  MTD - Prior","description":null,"expression":"CASE WHEN jed >= date_trunc(''month'',
  current_date) - interval ''1 year''\n              AND jed < date_trunc(''month'',
  current_date) - interval ''1 year'' + (current_date - date_trunc(''month'', current_date))
  \n         THEN actual_income\n         ELSE 0 \n    END","filterable":true,"groupby":true,"id":4321,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  MTD Prev Year","optionName":"metric_968tmk1trxg_u1iobj3ns0m","sqlExpression":null},"Monthly
  Avg Revenue",{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  YTD - Current","description":null,"expression":"CASE \n        WHEN jed >= date_trunc(''year'',
  current_date)\n             AND jed < current_date\n        THEN actual_income\n        ELSE
  0\n    END\n","filterable":true,"groupby":true,"id":683,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  YTD","optionName":"metric_a1amgf20y7_uf10zbeqxr","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Revenue
  YTD - Previous","description":null,"expression":"CASE\n     WHEN jed >= date_trunc(''year'',
  current_date - interval ''1 year'') \n             AND jed < (current_date - interval
  ''1 year'') \n    THEN actual_income\n    ELSE 0\nEND","filterable":true,"groupby":true,"id":2180,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":null,"type_generic":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Revenue
  YTD Prev Year","optionName":"metric_30tefznun1_9uumtmd2yst","sqlExpression":null}],"metricsLayout":"COLUMNS","adhoc_filters":[{"expressionType":"SIMPLE","subject":"jed","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":true,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_4qedl6zb4ze_6wlwjkefpij"}],"row_limit":"100000","order_desc":true,"aggregateFunction":"Sum","colTotals":true,"valueFormat":"SMART_NUMBER","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[{"column":"Revenue
  This Week","colorScheme":"#E8EBFE","operator":"None"},{"column":"Revenue Prev Week","colorScheme":"#E0F0FF","operator":"None"},{"column":"Weekly
  Avg Revenue","colorScheme":"#FFEF9D","operator":"None"},{"column":"Revenue MTD","colorScheme":"#E6FFFB","operator":"None"},{"column":"Revenue
  MTD Prev Year","colorScheme":"#87E8DE","operator":"None"},{"column":"Monthly Avg
  Revenue","colorScheme":"#EAFF8F","operator":"None"},{"column":"Monthly Avg Revenue","colorScheme":"#E0F0FF","operator":"None"},{"column":"Revenue
  YTD Prev Year","colorScheme":"#E8EBFE","operator":"None"}],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: e1d74174-e942-4085-b016-2f92d79cf0bc
version: 1.0.0
dataset_uuid: ed854b24-dc83-420a-b942-0ac77d1d6be1
