slice_name: SI Filed Today
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 75__table
  viz_type: big_number_total
  slice_id: 108
  metric:
    aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: ship_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 618
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: SI
    optionName: metric_hv2lo7ucp9l_zncj41reqwo
    sqlExpression: null
  adhoc_filters:
  - expressionType: SIMPLE
    subject: ship_type
    operator: IN
    operatorId: IN
    comparator:
    - back_to_back
    - consol
    - direct
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_30xg6z3vu6x_4ad5yr17fq9
  - expressionType: SQL
    sqlExpression: si_filed_at is not NULL
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_8n0h24fhzrr_l0u2egorf1
  - expressionType: SQL
    sqlExpression: si_filed_at=CURRENT_DATE
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_h34w5zbypj9_kpk3uc42wv8
  - expressionType: SIMPLE
    subject: etd
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_n7vw61xcq8_sbz67rk5ure
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 97847849-9111-4cc2-a36b-0e4fe3787249
version: 1.0.0
dataset_uuid: 4fc51f9b-3504-4494-9dde-c1ff47aec07c
