slice_name: Top 10 Trade-Lanes by TEUs - OE
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 70__table
  viz_type: echarts_timeseries_bar
  slice_id: 923
  x_axis: trade_lane
  x_axis_sort_asc: true
  x_axis_sort_series: max
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TEUs YTD - Current
      description: null
      expression: "CASE \n    WHEN jed >= date_trunc('year', current_date) \n    \
        \     AND jed < current_date\n    THEN teu_count\n    ELSE 0 \nEND"
      filterable: true
      groupby: true
      id: 3232
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(TEUs YTD - Current)
    optionName: metric_qqkw1d26ni_4izxfs0qpsi
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TEUs YTD - Previous
      description: null
      expression: "CASE \n    WHEN jed >= date_trunc('year', current_date) - interval\
        \ '1 year'\n         AND jed < (current_date - interval '1 year')\n    THEN\
        \ teu_count\n    ELSE 0 \nEND"
      filterable: true
      groupby: true
      id: 3231
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(TEUs YTD - Previous)
    optionName: metric_u1iqi0uf0i_4528fp5kfnb
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_yx661pj6glh_6sjd08qjewg
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_m1sp9jxp8y_9tli6bn9t5m
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_kx4z3qrmqj_8hhy1swm2uq
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: horizontal
  x_axis_title: ''
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: shipmnts_colors
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelRotation: 0
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 64
query_context: null
cache_timeout: null
uuid: 81052dd1-c840-482e-9788-dc4e48d0ac8c
version: 1.0.0
dataset_uuid: 1796121c-92ed-4c17-bbdc-0169cf3c1c17
