slice_name: Top 10 Customers by GP - OE
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 71__table
  viz_type: echarts_timeseries_bar
  slice_id: 913
  x_axis: customer_sf
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: GP YTD - Current
      description: GP YTD till the current date
      expression: "CASE \n        WHEN jed >= date_trunc('year', current_date)\n \
        \            AND jed < current_date\n        THEN actual_gp\n        ELSE\
        \ 0\n    END"
      filterable: true
      groupby: true
      id: 680
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Margin YTD
    optionName: metric_l56ju3qq7a_t44f1ajt2o8
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: GP YTD - Previous
      description: GP Previous Year - But not upto the same YTD
      expression: "CASE \n        WHEN jed >= date_trunc('year', current_date - interval\
        \ '1 year') \n             AND jed < (current_date - interval '1 year') \n\
        \        THEN actual_gp \n        ELSE 0 \n    END"
      filterable: true
      groupby: true
      id: 2179
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Margin YTD Prev Year
    optionName: metric_25boht044w8_vydzzeze7tc
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator:
    - ocean
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_51l3x06mray_x7lvr666l3i
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: freight
  - clause: WHERE
    comparator:
    - export
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ayvpi6qq3gr_3iqp094bp2x
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: trade
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_4qedl6zb4ze_6wlwjkefpij
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: jed
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: horizontal
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: shipmnts_colors
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 64
query_context: null
cache_timeout: null
uuid: d6444ad0-996d-4ba6-b8a9-fd72a90e43db
version: 1.0.0
dataset_uuid: ed854b24-dc83-420a-b942-0ac77d1d6be1
