slice_name: Vessel Wise Container Allotment
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 77__table
  viz_type: pivot_table_v2
  slice_id: 594
  groupbyColumns: []
  groupbyRows:
  - vessel_voyage
  - pod
  - datasourceWarning: false
    expressionType: SQL
    label: Container code
    sqlExpression: container_type
  - datasourceWarning: false
    expressionType: SQL
    label: Customer
    sqlExpression: customer
  time_grain_sqla: P1D
  temporal_columns_lookup:
    booking_date: true
    created_at: true
    doc_cutoff_date: true
    estimated_time_of_departure: true
    si_cutoff_date: true
    valid_till_date: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: received
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 3050
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: Received
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Received
    optionName: metric_95d6wpax1q_9ue79nb7n7
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Alloted Count
      description: null
      expression: CASE WHEN shipment_id is not null then requested_containers_count
        ELSE 0 END
      filterable: true
      groupby: true
      id: 3056
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Alloted
    optionName: metric_c356nupx41v_rbm914phos
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: pending
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 3053
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: Pending
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Pending
    optionName: metric_acp7e56plqu_2a0l7kxsxz2
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Expired Count
      description: null
      expression: CASE WHEN CURRENT_DATE > valid_till_date::DATE AND pending>0 THEN
        pending ELSE 0 END
      filterable: true
      groupby: true
      id: 3684
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: null
      type_generic: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Expired
    optionName: metric_cb942txsbdb_qa6n4nxeod9
    sqlExpression: null
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_e3qg82qw60l_x3p37ihpz3
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: vessel_voyage!='-'
    subject: null
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_3o1qpqk93vl_v61nqwykzii
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: estimated_time_of_departure
  row_limit: 1000
  order_desc: true
  aggregateFunction: Sum
  expandCollapse: true
  rowSubTotals: false
  colTotals: true
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting:
  - colorScheme: '#E8EBFE'
    column: Received
    operator: None
  - colorScheme: '#CDFEE1'
    column: Alloted
    operator: None
  - colorScheme: '#FFEF9D'
    column: Pending
    operator: None
  - colorScheme: '#FEDAD9'
    column: Expired
    operator: None
  extra_form_data: {}
  dashboards:
  - 6
  - 58
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: bfbd2e14-bae2-4346-94c1-1e98da0cfa2b
version: 1.0.0
dataset_uuid: d9d11ad6-1020-4592-835f-4399ab9a9647
